# Generated by Django 4.0.3 on 2022-03-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadre',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cadre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('serialnumber', models.AutoField(primary_key=True, serialize=False)),
                ('nominationdate', models.DateField(blank=True, null=True)),
                ('whetherattended', models.BooleanField(blank=True, null=True)),
                ('dateattended', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('psnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('initial', models.CharField(blank=True, max_length=4, null=True)),
                ('firstname', models.CharField(blank=True, max_length=40, null=True)),
                ('middlename', models.CharField(blank=True, max_length=40, null=True)),
                ('lastname', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'employeestatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'programtype',
                'managed': False,
            },
        ),
    ]
